---
vector_version: "0.58.0"
vector_install_dir: "/usr/local/bin"
vector_config_dir: "/etc/vector"
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
